default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: brezan_development
  host: db
  username: postgres
  password:

test:
  <<: *default
  database: brezan_test

production:
  url: <%= ENV['DATABASE_URL'] %>
